<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['ntp_app_description'] = 'Приложение NTP-сервер предоставляет услуги протокола сетевого времени для ваших систем. Компьютеры и Интернет устройства могут синхронизировать свои часы на этом сервере, чтобы обеспечить высокую степень точности времени.';
$lang['ntp_app_name'] = 'NTP Сервер';
$lang['ntp_time_server_thank_you'] = 'Отдельное спасибо ClearCenter для обеспечения серверов времени.';
$lang['ntp_time_servers'] = 'Серверы времени';
