<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['ntp_app_description'] = 'The NTP Server app provides the network time protocol service for your systems.  Computers and Internet devices can synchronize their clocks against this server to achieve a  high degree of time accuracy.';
$lang['ntp_app_name'] = 'NTP Server';
$lang['ntp_time_server_thank_you'] = 'Special thanks to ClearCenter for providing time servers.';
$lang['ntp_time_servers'] = 'Time Servers';
