<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['ntp_app_description'] = 'Aplikacja serwera NTP dodaje obsługę serwera czasu dla Twoich systemów.  Komputery oraz urządzenia sieciowe mogą synchronizować swój czas z zegarem serwera aby osiągnąć  wysoki stopień dokładności czasu.';
$lang['ntp_app_name'] = 'Serwer NTP';
$lang['ntp_time_server_thank_you'] = 'Specjalne podziękowania dla ClearCenter za udostępnienie serwerów czasu.';
$lang['ntp_time_servers'] = 'Serwery czasu';
